"""Auth user id

Revision ID: e2c2d4fe34f1
Revises: cdb1cd1ef17f
Create Date: 2023-03-16 21:13:20.798843

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'e2c2d4fe34f1'
down_revision = 'cdb1cd1ef17f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auth_user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'auth_user_id')
    # ### end Alembic commands ###
